version: '3'

services:
  apigateway:
    image: apigateway:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_apigateway$
    volumes:
      - C:\Tulasi\APIGatewayTest\ApiGateway:/app
      - C:\Users\taparu\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_apigateway$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_apigateway$ bin/Debug/netcoreapp2.1/ApiGateway.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
